### ISSUE TITLE
Model load: RuntimeError: vector::_M_default_append

### ISSUE THREAD

**Issue by schnapi** [vrasneur/pyfasttext#17]
When I try to load a model `lid.176.bin` from https://fasttext.cc/docs/en/language-identification.html
I get this error.
```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    model = FastText('langdetect.bin')
  File "src/pyfasttext.pyx", line 123, in pyfasttext.FastText.__cinit__
  File "src/pyfasttext.pyx", line 437, in pyfasttext.FastText.load_model
RuntimeError: vector::_M_default_append
```

Thanks!

**Comment by vrasneur** [comment]
See #16

I  have released a new version (0.4.0) that supports the new models.
You should update the module.
