### ISSUE TITLE
Error Installing pyfasttext with pip 

### ISSUE THREAD

**Issue by nalsabhan** [vrasneur/pyfasttext#22]
I have installed cysignals prior to installing pyfasttext. 

-  Python 2.7.12 :: Continuum Analytics, Inc.
-  2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17) 
 [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]
-  ProductName:	Mac OS X
-  ProductVersion:	10.12.6
-  BuildVersion:	16G29
- cython.__version__ : 0.27.2

```
>> pip install pyfasttext
Collecting pyfasttext
  Using cached pyfasttext-0.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l4/hwj373l934q3c119q47tw_2m0000gn/T/pip-build-0BqpqF/pyfasttext/setup.py", line 78, in <module>
        'FASTTEXT_VERSION': get_fasttext_commit_hash()}),
      File "/Users/nawafalsabhan/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 920, in cythonize
        aliases=aliases)
      File "/Users/nawafalsabhan/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 742, in create_extension_list
        elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      File "/Users/nawafalsabhan/anaconda/lib/python2.7/abc.py", line 144, in __instancecheck__
        return cls.__subclasscheck__(subtype)
      File "/Users/nawafalsabhan/anaconda/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/Users/nawafalsabhan/anaconda/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/Users/nawafalsabhan/anaconda/lib/python2.7/abc.py", line 161, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/Users/nawafalsabhan/anaconda/lib/python2.7/site-packages/backports_abc.py", line 66, in __subclasshook__
        mro = C.__mro__
    AttributeError: class Extension has no attribute '__mro__'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l4/hwj373l934q3c119q47tw_2m0000gn/T/pip-build-0BqpqF/pyfasttext/
```

**Comment by vrasneur** [comment]
Hi @nalsabhan,

The bug should be fixed, but I have not released a new version yet.

Can you try to update the source code and compile manually ? (see the README for the required steps).
