### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sosoxuc** [vrasneur/pyfasttext#48]
If I install `pyfasttext` on a fresh env I have an error while importing pyfasttext:
```
docker run -i -t python:3.6-slim /bin/bash
```

```
apt-get -y update && apt-get -y install make python3-dev gcc g++
pip3 install Cython cysignals
pip3 install pyfasttext
```

```python```>>>```import pyfasttext```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__init__.pxd", line 918, in init pyfasttext
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

If I install old version and then upgrade:
```
pip3 install pyfasttext==0.4.5
pip3 install pyfasttext==0.4.6
```
everything works fine.

**Comment by QuarKUS7** [comment]
I solved the same issue by updating numpy to 1.16.0.
